### PR TITLE
feat : point charge 구현

### PR DESCRIPTION
**Pull request by rlatmd0829**
test

### CODE REVIEW

**Comment by K-J-HYEON** [comment]
check

**Comment by dev-jinius** [comment]
check!

**Review by K-J-HYEON — APPROVED** [review]
check!

**Review by dev-jinius — APPROVED** [review]
I agree!!

**Review by dev-jinius — APPROVED** [review]
approve

**Comment by K-J-HYEON** [comment]
approve

**Comment by K-J-HYEON** [comment]
approve

**Review by K-J-HYEON — APPROVED** [review]

**Review by K-J-HYEON — APPROVED** [review]
check!

**Review by dev-jinius — APPROVED** [review]
RE approve

**Pull request merged**
